name: release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]

    name: Publish
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unshallow Repository
        run: git fetch --prune --unshallow

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Setup Gradle Caching
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: java-${{ matrix.java }}
          gradle-version: wrapper
          save-generated-gradle-jars: true
          save-local-build-cache: true
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Give Gradle Execute Permissions
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: chmod +x ./gradlew

      - name: Generate Changelog File
        run: ./gradlew gitChangelogTask
        env:
          GENERATE_CHANGELOG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project JARs
        run: ./gradlew build

      - name: Upload Artifacts to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Project-Jars
          path: ./build/libs

      - name: Upload Changelog to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: ./CHANGELOG.md

      - name: Publish Project to Maven
        run: ./gradlew publish
        env:
          APEX_MODS_MAVEN_USERNAME: ${{ secrets.APEX_MODS_MAVEN_USERNAME }}
          APEX_MODS_MAVEN_PASSWORD: ${{ secrets.APEX_MODS_MAVEN_PASSWORD }}

      - name: Stop Gradle Deamons
        run: ./gradlew --stop

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties