# GitHub Action to auto-magically publish versions
# for tagged commits
name: release

# Run on every push (with version tag)
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-18.04

    steps:
      # Checkout repository & Setup JDK
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      # Setup & Restore caches
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./build
          key: ${{ runner.os }}-gradle

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper

      # Validate Gradle Wrapper
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew

      # Generate Changelog
      - run: ./gradlew gitChangelogTask
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build package
      - run: ./gradlew build

      # Upload artifacts to GitHub Actions
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build/libs

      # Upload changelog to GitHub Actions
      - uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: ./CHANGELOG.md

      # Publish to GitHub Packages
      - run: ./gradlew publish
        env:
          APEX_MODS_MAVEN_USERNAME: ${{ secrets.APEX_MODS_MAVEN_USERNAME }}
          APEX_MODS_MAVEN_PASSWORD: ${{ secrets.APEX_MODS_MAVEN_PASSWORD }}

      # Kill gradlew deamon (caching requires gradle to not be running)
      - run: ./gradlew --stop

      # Remove problematic files
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties